name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main  # Trigger deployment when merging into main

env:
  IMAGE_NAME: whatsapp-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for linux/amd64
        run: |
          IMAGE_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}
          docker buildx build --platform linux/amd64 -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest --push .

      - name: Deploy to Azure Container Apps with direct Azure CLI
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --set-env-vars \
              AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} \
              ALGORITHM="HS256" \
              DATABASE_NAME="db_name" \
              SMTP_HOST="smtp.zoho.eu" \
              SMTP_PORT=${{ secrets.SMTP_PORT }} \
              SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
              SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
              SMTP_SENDER=${{ secrets.SMTP_SENDER }} \
              BASE_URL=${{ secrets.BASE_URL }} \
              MONGODB_URI=${{ secrets.MONGODB_URI }} \
              WHATSAPP_VERIFY_TOKEN=${{ secrets.WHATSAPP_VERIFY_TOKEN }} \
              WHATSAPP_ID=${{ secrets.WHATSAPP_ID }} \
              WHATSAPP_VERSION=${{ secrets.WHATSAPP_VERSION }} \
              WHATSAPP_PHONE_NUMBER_ID=${{ secrets.WHATSAPP_PHONE_NUMBER_ID }} \
              WHATSAPP_SECRET=${{ secrets.WHATSAPP_SECRET }} \
              AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} \
              AZURE_OPENAI_DEPLOYMENT=${{ secrets.AZURE_OPENAI_DEPLOYMENT }} \
              AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }} \
              WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }} \
              RECIPIENT_WAID=${{ secrets.RECIPIENT_WAID }} \
              JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
              
