name: Trigger auto deployment for klaro-whatsapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/klaro-whatsapp-AutoDeployTrigger-18b5915f-d2aa-4af4-ab37-a088e1e0ff1c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KLAROWHATSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KLAROWHATSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KLAROWHATSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.KLAROWHATSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KLAROWHATSAPP_REGISTRY_PASSWORD }}
          containerAppName: klaro-whatsapp
          resourceGroup: rg-common-ai
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


